package com.uton.carsokApi.dao;


import com.uton.carsokApi.model.CarsokCarNews;

import java.util.List;
import java.util.Map;

public interface CarsokCarNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_car_news
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_car_news
     *
     * @mbggenerated
     */
    int insert(CarsokCarNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_car_news
     *
     * @mbggenerated
     */
    int insertSelective(CarsokCarNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_car_news
     *
     * @mbggenerated
     */
    CarsokCarNews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_car_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarsokCarNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_car_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CarsokCarNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_car_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarsokCarNews record);

    CarsokCarNews selectNewCarNewsLimit(Map param);
}