package com.uton.carsokApi.dao;

import com.uton.carsokApi.controller.request.CarsokAdviceRequest;
import com.uton.carsokApi.model.CarsokAdvice;

public interface CarsokAdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_advice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_advice
     *
     * @mbggenerated
     */
    int insert(CarsokAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_advice
     *
     * @mbggenerated
     */
    int insertSelective(CarsokAdviceRequest carsokAdviceRequest);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_advice
     *
     * @mbggenerated
     */
    CarsokAdvice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_advice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarsokAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_advice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CarsokAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_advice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarsokAdvice record);
}