package com.uton.carsokApi.dao;

import com.uton.carsokApi.model.DailyCheckProductInfo;
import com.uton.carsokApi.model.DailycheckDispatcher;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DailycheckDispatcherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_dailycheck_Dispatcher
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_dailycheck_Dispatcher
     *
     * @mbggenerated
     */
    int insert(DailycheckDispatcher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_dailycheck_Dispatcher
     *
     * @mbggenerated
     */
    int insertSelective(DailycheckDispatcher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_dailycheck_Dispatcher
     *
     * @mbggenerated
     */
    DailycheckDispatcher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_dailycheck_Dispatcher
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DailycheckDispatcher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_dailycheck_Dispatcher
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DailycheckDispatcher record);

    List<DailyCheckProductInfo> getDispatcherList(@Param("accountId")String accountId,@Param("checker")String checker,@Param("checkDate")String checkDate);

    List<DailycheckDispatcher> getDispatcherCheckerList(@Param("accountId")String accountId);

    List<DailycheckDispatcher> getDispatcherCheckerInfoList(@Param("accountId")String accountId);

    int deleteByAccount(@Param("accountId")String accountId);
}