package com.uton.carsokApi.dao;

import com.uton.carsokApi.model.Employees;

import java.util.List;

public interface EmployeesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_loan_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_loan_user
     *
     * @mbggenerated
     */
    int insert(Employees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_loan_user
     *
     * @mbggenerated
     */
    int insertSelective(Employees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_loan_user
     *
     * @mbggenerated
     */
    Employees selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_loan_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Employees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_loan_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Employees record);

    List<Employees> selectAll();
}