package com.uton.carsokApi.dao;

import com.uton.carsokApi.model.LoanUser;
import org.apache.ibatis.annotations.Param;

public interface LoanUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_employees
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_employees
     *
     * @mbggenerated
     */
    int insert(LoanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_employees
     *
     * @mbggenerated
     */
    int insertSelective(LoanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_employees
     *
     * @mbggenerated
     */
    LoanUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_employees
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LoanUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_employees
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LoanUser record);

    int selectByAccountId(@Param("accountId") String accountId,@Param("role")String role);
}