package com.uton.carsokApi.dao;

import com.github.pagehelper.Page;
import com.uton.carsokApi.model.Poster;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface PosterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_poster
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_poster
     *
     * @mbggenerated
     */
    int insert(Poster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_poster
     *
     * @mbggenerated
     */
    int insertSelective(Poster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_poster
     *
     * @mbggenerated
     */
    Poster selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_poster
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Poster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carsok_poster
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Poster record);

    Page<Poster> selectAllByPage();

    List<Poster> selectPostByDate();
}