package com.uton.carsokApi.dao;

import com.uton.carsokApi.controller.response.ShareRankList;
import com.uton.carsokApi.controller.response.ShareRankResponse;
import com.uton.carsokApi.model.PushContent;
import com.uton.carsokApi.model.ShareRecord;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface ShareRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated
     */
    int insert(ShareRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated
     */
    int insertSelective(ShareRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated
     */
    ShareRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShareRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShareRecord record);

    /**
     * 查询手机号是主账号或子帐号
     */
    List<ShareRankResponse> shareRankList(String mobile);

    /**
     * 按天排行
     */
    List<Map> queryRankingCountByDay(List list);

    /**
     * 按周排行
     */
    List<Map> queryRankingCountByWeek(List list);

    /**
     * 按月排行
     */
    List<Map> queryRankingCountByMonth(List list);

    /**
     * 查询所有推送消息
     */
    List<PushContent> selectMessageList(@Param("pushTo")String pushTo,@Param("p1")int p1,@Param("p2")int p2);

    /**
     * 查询一共多少条
     */
    int selectMessageCount(@Param("pushTo")String pushTo);

    String getAcountPhone(@Param("productId")Integer productId);
}