package com.uton.carsokApi.dao;

import com.uton.carsokApi.model.TCarBrand;

import java.util.List;

public interface TCarBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brand
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brand
     *
     * @mbggenerated
     */
    int insert(TCarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brand
     *
     * @mbggenerated
     */
    int insertSelective(TCarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brand
     *
     * @mbggenerated
     */
    TCarBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brand
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TCarBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brand
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TCarBrand record);

    List<String> searchAllInitial();

    List<TCarBrand> searchAllBrand();

	String selectByCarBrand(String parameter);
}