package com.uton.carsokApi.dao;

import com.uton.carsokApi.model.TCarSeries;

import java.util.List;

public interface TCarSeriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_series
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_series
     *
     * @mbggenerated
     */
    int insert(TCarSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_series
     *
     * @mbggenerated
     */
    int insertSelective(TCarSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_series
     *
     * @mbggenerated
     */
    TCarSeries selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_series
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TCarSeries record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_series
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TCarSeries record);

    List<String> searchAllGroup(Integer brandId);

    List<TCarSeries> searchAllSeries(Integer brandId);
}