package com.uton.carsokApi.dao;

import com.uton.carsokApi.controller.response.CarModelsResponse;
import com.uton.carsokApi.model.TCarModel;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TCarModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_model
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_model
     *
     * @mbggenerated
     */
    int insert(TCarModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_model
     *
     * @mbggenerated
     */
    int insertSelective(TCarModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_model
     *
     * @mbggenerated
     */
    TCarModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_model
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TCarModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_model
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TCarModel record);

    List<String> searchAllModelYear(Integer seriesId);

    List<TCarModel> searchAllModel(Integer seriesId);

    List<CarModelsResponse> searchCarModelsByKey(@Param("keyword") String keyword, @Param("startNum")int startNum, @Param("size")int size);
}