package com.uton.carsokApi.model;

import java.util.Date;

public class CarsokCarNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_car_news.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_car_news.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_car_news.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_car_news.pic_url
     *
     * @mbggenerated
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_car_news.click_url
     *
     * @mbggenerated
     */
    private String clickUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_car_news.sort_num
     *
     * @mbggenerated
     */
    private Integer sortNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_car_news.createDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_car_news.updateDate
     *
     * @mbggenerated
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_car_news.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_car_news.id
     *
     * @return the value of carsok_car_news.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_car_news.id
     *
     * @param id the value for carsok_car_news.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_car_news.group_id
     *
     * @return the value of carsok_car_news.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_car_news.group_id
     *
     * @param groupId the value for carsok_car_news.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_car_news.title
     *
     * @return the value of carsok_car_news.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_car_news.title
     *
     * @param title the value for carsok_car_news.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_car_news.pic_url
     *
     * @return the value of carsok_car_news.pic_url
     *
     * @mbggenerated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_car_news.pic_url
     *
     * @param picUrl the value for carsok_car_news.pic_url
     *
     * @mbggenerated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_car_news.click_url
     *
     * @return the value of carsok_car_news.click_url
     *
     * @mbggenerated
     */
    public String getClickUrl() {
        return clickUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_car_news.click_url
     *
     * @param clickUrl the value for carsok_car_news.click_url
     *
     * @mbggenerated
     */
    public void setClickUrl(String clickUrl) {
        this.clickUrl = clickUrl == null ? null : clickUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_car_news.sort_num
     *
     * @return the value of carsok_car_news.sort_num
     *
     * @mbggenerated
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_car_news.sort_num
     *
     * @param sortNum the value for carsok_car_news.sort_num
     *
     * @mbggenerated
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_car_news.createDate
     *
     * @return the value of carsok_car_news.createDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_car_news.createDate
     *
     * @param createdate the value for carsok_car_news.createDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_car_news.updateDate
     *
     * @return the value of carsok_car_news.updateDate
     *
     * @mbggenerated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_car_news.updateDate
     *
     * @param updatedate the value for carsok_car_news.updateDate
     *
     * @mbggenerated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_car_news.remarks
     *
     * @return the value of carsok_car_news.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_car_news.remarks
     *
     * @param remarks the value for carsok_car_news.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}