package com.uton.carsokApi.model;

import java.util.Date;

public class CarsokAppVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_app_version.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_app_version.app_version
     *
     * @mbggenerated
     */
    private String appVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_app_version.is_force_update
     *
     * @mbggenerated
     */
    private Short isForceUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_app_version.download_url
     *
     * @mbggenerated
     */
    private String downloadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_app_version.is_last
     *
     * @mbggenerated
     */
    private Short isLast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_app_version.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_app_version.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_app_version.distinction
     *
     * @mbggenerated
     */
    private String distinction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_app_version.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_app_version.id
     *
     * @return the value of carsok_app_version.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_app_version.id
     *
     * @param id the value for carsok_app_version.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_app_version.app_version
     *
     * @return the value of carsok_app_version.app_version
     *
     * @mbggenerated
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_app_version.app_version
     *
     * @param appVersion the value for carsok_app_version.app_version
     *
     * @mbggenerated
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_app_version.is_force_update
     *
     * @return the value of carsok_app_version.is_force_update
     *
     * @mbggenerated
     */
    public Short getIsForceUpdate() {
        return isForceUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_app_version.is_force_update
     *
     * @param isForceUpdate the value for carsok_app_version.is_force_update
     *
     * @mbggenerated
     */
    public void setIsForceUpdate(Short isForceUpdate) {
        this.isForceUpdate = isForceUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_app_version.download_url
     *
     * @return the value of carsok_app_version.download_url
     *
     * @mbggenerated
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_app_version.download_url
     *
     * @param downloadUrl the value for carsok_app_version.download_url
     *
     * @mbggenerated
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl == null ? null : downloadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_app_version.is_last
     *
     * @return the value of carsok_app_version.is_last
     *
     * @mbggenerated
     */
    public Short getIsLast() {
        return isLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_app_version.is_last
     *
     * @param isLast the value for carsok_app_version.is_last
     *
     * @mbggenerated
     */
    public void setIsLast(Short isLast) {
        this.isLast = isLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_app_version.create_time
     *
     * @return the value of carsok_app_version.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_app_version.create_time
     *
     * @param createTime the value for carsok_app_version.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_app_version.update_time
     *
     * @return the value of carsok_app_version.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_app_version.update_time
     *
     * @param updateTime the value for carsok_app_version.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_app_version.distinction
     *
     * @return the value of carsok_app_version.distinction
     *
     * @mbggenerated
     */
    public String getDistinction() {
        return distinction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_app_version.distinction
     *
     * @param distinction the value for carsok_app_version.distinction
     *
     * @mbggenerated
     */
    public void setDistinction(String distinction) {
        this.distinction = distinction == null ? null : distinction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_app_version.description
     *
     * @return the value of carsok_app_version.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_app_version.description
     *
     * @param description the value for carsok_app_version.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}