package com.uton.carsokApi.model;

public class CarsokAdvice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_advice.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_advice.account_code
     *
     * @mbggenerated
     */
    private String accountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_advice.contact_info
     *
     * @mbggenerated
     */
    private String contactInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_advice.solution
     *
     * @mbggenerated
     */
    private Integer solution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_advice.advice_type
     *
     * @mbggenerated
     */
    private String adviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_advice.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_advice.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_advice.id
     *
     * @return the value of carsok_advice.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_advice.id
     *
     * @param id the value for carsok_advice.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_advice.account_code
     *
     * @return the value of carsok_advice.account_code
     *
     * @mbggenerated
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_advice.account_code
     *
     * @param accountCode the value for carsok_advice.account_code
     *
     * @mbggenerated
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode == null ? null : accountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_advice.contact_info
     *
     * @return the value of carsok_advice.contact_info
     *
     * @mbggenerated
     */
    public String getContactInfo() {
        return contactInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_advice.contact_info
     *
     * @param contactInfo the value for carsok_advice.contact_info
     *
     * @mbggenerated
     */
    public void setContactInfo(String contactInfo) {
        this.contactInfo = contactInfo == null ? null : contactInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_advice.solution
     *
     * @return the value of carsok_advice.solution
     *
     * @mbggenerated
     */
    public Integer getSolution() {
        return solution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_advice.solution
     *
     * @param solution the value for carsok_advice.solution
     *
     * @mbggenerated
     */
    public void setSolution(Integer solution) {
        this.solution = solution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_advice.advice_type
     *
     * @return the value of carsok_advice.advice_type
     *
     * @mbggenerated
     */
    public String getAdviceType() {
        return adviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_advice.advice_type
     *
     * @param adviceType the value for carsok_advice.advice_type
     *
     * @mbggenerated
     */
    public void setAdviceType(String adviceType) {
        this.adviceType = adviceType == null ? null : adviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_advice.create_time
     *
     * @return the value of carsok_advice.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_advice.create_time
     *
     * @param createTime the value for carsok_advice.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_advice.content
     *
     * @return the value of carsok_advice.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_advice.content
     *
     * @param content the value for carsok_advice.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}