package com.uton.carsokApi.model;

import java.util.Date;

public class DailycheckChecker {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_checker.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_checker.result
     *
     * @mbggenerated
     */
    private String accountId;

    private String checker;

    private Date createTime;

    private Date updateTime;

    private Integer enable;


    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_checker.id
     *
     * @param id the value for carsok_dailycheck_checker.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_checker.checker
     *
     * @return the value of carsok_dailycheck_checker.checker
     *
     * @mbggenerated
     */
    public String getChecker() {
        return checker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_checker.checker
     *
     * @param checker the value for carsok_dailycheck_checker.checker
     *
     * @mbggenerated
     */
    public void setChecker(String checker) {
        this.checker = checker == null ? null : checker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_checker.create_time
     *
     * @return the value of carsok_dailycheck_checker.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_checker.create_time
     *
     * @param createTime the value for carsok_dailycheck_checker.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_checker.update_time
     *
     * @return the value of carsok_dailycheck_checker.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_checker.update_time
     *
     * @param updateTime the value for carsok_dailycheck_checker.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_checker.enable
     *
     * @return the value of carsok_dailycheck_checker.enable
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_checker.enable
     *
     * @param enable the value for carsok_dailycheck_checker.enable
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }
}