package com.uton.carsokApi.model;

import java.util.Date;

public class DailycheckResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_result.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_result.result
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_result.checker
     *
     * @mbggenerated
     */
    private String checker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_result.is_check
     *
     * @mbggenerated
     */
    private Integer isCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_result.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_result.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_result.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_result.enable
     *
     * @mbggenerated
     */
    private Integer enable;


    private String checkDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_result.id
     *
     * @return the value of carsok_dailycheck_result.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_result.id
     *
     * @param id the value for carsok_dailycheck_result.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_result.result
     *
     * @return the value of carsok_dailycheck_result.result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_result.result
     *
     * @param result the value for carsok_dailycheck_result.result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_result.checker
     *
     * @return the value of carsok_dailycheck_result.checker
     *
     * @mbggenerated
     */
    public String getChecker() {
        return checker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_result.checker
     *
     * @param checker the value for carsok_dailycheck_result.checker
     *
     * @mbggenerated
     */
    public void setChecker(String checker) {
        this.checker = checker == null ? null : checker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_result.is_check
     *
     * @return the value of carsok_dailycheck_result.is_check
     *
     * @mbggenerated
     */
    public Integer getIsCheck() {
        return isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_result.is_check
     *
     * @param isCheck the value for carsok_dailycheck_result.is_check
     *
     * @mbggenerated
     */
    public void setIsCheck(Integer isCheck) {
        this.isCheck = isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_result.product_id
     *
     * @return the value of carsok_dailycheck_result.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_result.product_id
     *
     * @param productId the value for carsok_dailycheck_result.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_result.create_time
     *
     * @return the value of carsok_dailycheck_result.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_result.create_time
     *
     * @param createTime the value for carsok_dailycheck_result.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_result.update_time
     *
     * @return the value of carsok_dailycheck_result.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_result.update_time
     *
     * @param updateTime the value for carsok_dailycheck_result.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_result.enable
     *
     * @return the value of carsok_dailycheck_result.enable
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_result.enable
     *
     * @param enable the value for carsok_dailycheck_result.enable
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    public String getCheckDate() {
        return checkDate;
    }

    public void setCheckDate(String checkDate) {
        this.checkDate = checkDate;
    }
}