package com.uton.carsokApi.model;

import java.util.Date;

public class DailycheckDispatcher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_Dispatcher.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_Dispatcher.account_id
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_Dispatcher.checker
     *
     * @mbggenerated
     */
    private String checker;

    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_Dispatcher.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_Dispatcher.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_dailycheck_Dispatcher.enable
     *
     * @mbggenerated
     */
    private Integer enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_Dispatcher.id
     *
     * @return the value of carsok_dailycheck_Dispatcher.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_Dispatcher.id
     *
     * @param id the value for carsok_dailycheck_Dispatcher.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_Dispatcher.account_id
     *
     * @return the value of carsok_dailycheck_Dispatcher.account_id
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_Dispatcher.account_id
     *
     * @param accountId the value for carsok_dailycheck_Dispatcher.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_Dispatcher.checker
     *
     * @return the value of carsok_dailycheck_Dispatcher.checker
     *
     * @mbggenerated
     */
    public String getChecker() {
        return checker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_Dispatcher.checker
     *
     * @param checker the value for carsok_dailycheck_Dispatcher.checker
     *
     * @mbggenerated
     */
    public void setChecker(String checker) {
        this.checker = checker == null ? null : checker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_Dispatcher.create_time
     *
     * @return the value of carsok_dailycheck_Dispatcher.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_Dispatcher.create_time
     *
     * @param createTime the value for carsok_dailycheck_Dispatcher.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_Dispatcher.update_time
     *
     * @return the value of carsok_dailycheck_Dispatcher.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_Dispatcher.update_time
     *
     * @param updateTime the value for carsok_dailycheck_Dispatcher.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_dailycheck_Dispatcher.enable
     *
     * @return the value of carsok_dailycheck_Dispatcher.enable
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_dailycheck_Dispatcher.enable
     *
     * @param enable the value for carsok_dailycheck_Dispatcher.enable
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }
}