package com.uton.carsokApi.model;

import java.util.Date;

public class Poster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_poster.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_poster.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_poster.descr
     *
     * @mbggenerated
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_poster.pic_path
     *
     * @mbggenerated
     */
    private String picPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_poster.hot
     *
     * @mbggenerated
     */
    private Integer hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_poster.viewed
     *
     * @mbggenerated
     */
    private Integer viewed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_poster.shared
     *
     * @mbggenerated
     */
    private Integer shared;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_poster.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_poster.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carsok_poster.enable
     *
     * @mbggenerated
     */
    private Integer enable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_poster.id
     *
     * @return the value of carsok_poster.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_poster.id
     *
     * @param id the value for carsok_poster.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_poster.title
     *
     * @return the value of carsok_poster.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_poster.title
     *
     * @param title the value for carsok_poster.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_poster.descr
     *
     * @return the value of carsok_poster.descr
     *
     * @mbggenerated
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_poster.descr
     *
     * @param descr the value for carsok_poster.descr
     *
     * @mbggenerated
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_poster.pic_path
     *
     * @return the value of carsok_poster.pic_path
     *
     * @mbggenerated
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_poster.pic_path
     *
     * @param picPath the value for carsok_poster.pic_path
     *
     * @mbggenerated
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_poster.hot
     *
     * @return the value of carsok_poster.hot
     *
     * @mbggenerated
     */
    public Integer getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_poster.hot
     *
     * @param hot the value for carsok_poster.hot
     *
     * @mbggenerated
     */
    public void setHot(Integer hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_poster.viewed
     *
     * @return the value of carsok_poster.viewed
     *
     * @mbggenerated
     */
    public Integer getViewed() {
        return viewed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_poster.viewed
     *
     * @param viewed the value for carsok_poster.viewed
     *
     * @mbggenerated
     */
    public void setViewed(Integer viewed) {
        this.viewed = viewed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_poster.shared
     *
     * @return the value of carsok_poster.shared
     *
     * @mbggenerated
     */
    public Integer getShared() {
        return shared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_poster.shared
     *
     * @param shared the value for carsok_poster.shared
     *
     * @mbggenerated
     */
    public void setShared(Integer shared) {
        this.shared = shared;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_poster.create_time
     *
     * @return the value of carsok_poster.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_poster.create_time
     *
     * @param createTime the value for carsok_poster.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_poster.update_time
     *
     * @return the value of carsok_poster.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_poster.update_time
     *
     * @param updateTime the value for carsok_poster.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carsok_poster.enable
     *
     * @return the value of carsok_poster.enable
     *
     * @mbggenerated
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carsok_poster.enable
     *
     * @param enable the value for carsok_poster.enable
     *
     * @mbggenerated
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }
}