package com.uton.carsokApi.model;

import java.util.Date;

public class ShareRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_record.share_account_code
     *
     * @mbggenerated
     */
    private String shareAccountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column share_record.share_date
     *
     * @mbggenerated
     */
    private Date shareDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_record.id
     *
     * @return the value of share_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_record.id
     *
     * @param id the value for share_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_record.share_account_code
     *
     * @return the value of share_record.share_account_code
     *
     * @mbggenerated
     */
    public String getShareAccountCode() {
        return shareAccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_record.share_account_code
     *
     * @param shareAccountCode the value for share_record.share_account_code
     *
     * @mbggenerated
     */
    public void setShareAccountCode(String shareAccountCode) {
        this.shareAccountCode = shareAccountCode == null ? null : shareAccountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column share_record.share_date
     *
     * @return the value of share_record.share_date
     *
     * @mbggenerated
     */
    public Date getShareDate() {
        return shareDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column share_record.share_date
     *
     * @param shareDate the value for share_record.share_date
     *
     * @mbggenerated
     */
    public void setShareDate(Date shareDate) {
        this.shareDate = shareDate;
    }
}