package com.uton.carsokApi.model;

import java.util.Date;

public class TCarSeries {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_series.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_series.series_id
     *
     * @mbggenerated
     */
    private String seriesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_series.series_name
     *
     * @mbggenerated
     */
    private String seriesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_series.series_group_name
     *
     * @mbggenerated
     */
    private String seriesGroupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_series.brand_id
     *
     * @mbggenerated
     */
    private String brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_series.gmt_last_modify
     *
     * @mbggenerated
     */
    private Date gmtLastModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_series.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_series.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_series.enable
     *
     * @mbggenerated
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_series.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_series.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_series.id
     *
     * @return the value of t_car_series.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_series.id
     *
     * @param id the value for t_car_series.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_series.series_id
     *
     * @return the value of t_car_series.series_id
     *
     * @mbggenerated
     */
    public String getSeriesId() {
        return seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_series.series_id
     *
     * @param seriesId the value for t_car_series.series_id
     *
     * @mbggenerated
     */
    public void setSeriesId(String seriesId) {
        this.seriesId = seriesId == null ? null : seriesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_series.series_name
     *
     * @return the value of t_car_series.series_name
     *
     * @mbggenerated
     */
    public String getSeriesName() {
        return seriesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_series.series_name
     *
     * @param seriesName the value for t_car_series.series_name
     *
     * @mbggenerated
     */
    public void setSeriesName(String seriesName) {
        this.seriesName = seriesName == null ? null : seriesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_series.series_group_name
     *
     * @return the value of t_car_series.series_group_name
     *
     * @mbggenerated
     */
    public String getSeriesGroupName() {
        return seriesGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_series.series_group_name
     *
     * @param seriesGroupName the value for t_car_series.series_group_name
     *
     * @mbggenerated
     */
    public void setSeriesGroupName(String seriesGroupName) {
        this.seriesGroupName = seriesGroupName == null ? null : seriesGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_series.brand_id
     *
     * @return the value of t_car_series.brand_id
     *
     * @mbggenerated
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_series.brand_id
     *
     * @param brandId the value for t_car_series.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId == null ? null : brandId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_series.gmt_last_modify
     *
     * @return the value of t_car_series.gmt_last_modify
     *
     * @mbggenerated
     */
    public Date getGmtLastModify() {
        return gmtLastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_series.gmt_last_modify
     *
     * @param gmtLastModify the value for t_car_series.gmt_last_modify
     *
     * @mbggenerated
     */
    public void setGmtLastModify(Date gmtLastModify) {
        this.gmtLastModify = gmtLastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_series.gmt_create
     *
     * @return the value of t_car_series.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_series.gmt_create
     *
     * @param gmtCreate the value for t_car_series.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_series.gmt_modify
     *
     * @return the value of t_car_series.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_series.gmt_modify
     *
     * @param gmtModify the value for t_car_series.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_series.enable
     *
     * @return the value of t_car_series.enable
     *
     * @mbggenerated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_series.enable
     *
     * @param enable the value for t_car_series.enable
     *
     * @mbggenerated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_series.version
     *
     * @return the value of t_car_series.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_series.version
     *
     * @param version the value for t_car_series.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_series.memo
     *
     * @return the value of t_car_series.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_series.memo
     *
     * @param memo the value for t_car_series.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}