package com.uton.carsokApi.model;

import java.math.BigDecimal;
import java.util.Date;

public class TCarModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.model_id
     *
     * @mbggenerated
     */
    private String modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.model_name
     *
     * @mbggenerated
     */
    private String modelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.short_name
     *
     * @mbggenerated
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.model_price
     *
     * @mbggenerated
     */
    private BigDecimal modelPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.model_year
     *
     * @mbggenerated
     */
    private Integer modelYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.min_reg_year
     *
     * @mbggenerated
     */
    private Integer minRegYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.max_reg_year
     *
     * @mbggenerated
     */
    private Integer maxRegYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.liter
     *
     * @mbggenerated
     */
    private String liter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.gear_type
     *
     * @mbggenerated
     */
    private String gearType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.discharge_standard
     *
     * @mbggenerated
     */
    private String dischargeStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.seat_number
     *
     * @mbggenerated
     */
    private Integer seatNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.gmt_last_modify
     *
     * @mbggenerated
     */
    private Date gmtLastModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.enable
     *
     * @mbggenerated
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_model.series_id
     *
     * @mbggenerated
     */
    private String seriesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.id
     *
     * @return the value of t_car_model.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.id
     *
     * @param id the value for t_car_model.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.model_id
     *
     * @return the value of t_car_model.model_id
     *
     * @mbggenerated
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.model_id
     *
     * @param modelId the value for t_car_model.model_id
     *
     * @mbggenerated
     */
    public void setModelId(String modelId) {
        this.modelId = modelId == null ? null : modelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.model_name
     *
     * @return the value of t_car_model.model_name
     *
     * @mbggenerated
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.model_name
     *
     * @param modelName the value for t_car_model.model_name
     *
     * @mbggenerated
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.short_name
     *
     * @return the value of t_car_model.short_name
     *
     * @mbggenerated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.short_name
     *
     * @param shortName the value for t_car_model.short_name
     *
     * @mbggenerated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.model_price
     *
     * @return the value of t_car_model.model_price
     *
     * @mbggenerated
     */
    public BigDecimal getModelPrice() {
        return modelPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.model_price
     *
     * @param modelPrice the value for t_car_model.model_price
     *
     * @mbggenerated
     */
    public void setModelPrice(BigDecimal modelPrice) {
        this.modelPrice = modelPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.model_year
     *
     * @return the value of t_car_model.model_year
     *
     * @mbggenerated
     */
    public Integer getModelYear() {
        return modelYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.model_year
     *
     * @param modelYear the value for t_car_model.model_year
     *
     * @mbggenerated
     */
    public void setModelYear(Integer modelYear) {
        this.modelYear = modelYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.min_reg_year
     *
     * @return the value of t_car_model.min_reg_year
     *
     * @mbggenerated
     */
    public Integer getMinRegYear() {
        return minRegYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.min_reg_year
     *
     * @param minRegYear the value for t_car_model.min_reg_year
     *
     * @mbggenerated
     */
    public void setMinRegYear(Integer minRegYear) {
        this.minRegYear = minRegYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.max_reg_year
     *
     * @return the value of t_car_model.max_reg_year
     *
     * @mbggenerated
     */
    public Integer getMaxRegYear() {
        return maxRegYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.max_reg_year
     *
     * @param maxRegYear the value for t_car_model.max_reg_year
     *
     * @mbggenerated
     */
    public void setMaxRegYear(Integer maxRegYear) {
        this.maxRegYear = maxRegYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.liter
     *
     * @return the value of t_car_model.liter
     *
     * @mbggenerated
     */
    public String getLiter() {
        return liter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.liter
     *
     * @param liter the value for t_car_model.liter
     *
     * @mbggenerated
     */
    public void setLiter(String liter) {
        this.liter = liter == null ? null : liter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.gear_type
     *
     * @return the value of t_car_model.gear_type
     *
     * @mbggenerated
     */
    public String getGearType() {
        return gearType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.gear_type
     *
     * @param gearType the value for t_car_model.gear_type
     *
     * @mbggenerated
     */
    public void setGearType(String gearType) {
        this.gearType = gearType == null ? null : gearType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.discharge_standard
     *
     * @return the value of t_car_model.discharge_standard
     *
     * @mbggenerated
     */
    public String getDischargeStandard() {
        return dischargeStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.discharge_standard
     *
     * @param dischargeStandard the value for t_car_model.discharge_standard
     *
     * @mbggenerated
     */
    public void setDischargeStandard(String dischargeStandard) {
        this.dischargeStandard = dischargeStandard == null ? null : dischargeStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.seat_number
     *
     * @return the value of t_car_model.seat_number
     *
     * @mbggenerated
     */
    public Integer getSeatNumber() {
        return seatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.seat_number
     *
     * @param seatNumber the value for t_car_model.seat_number
     *
     * @mbggenerated
     */
    public void setSeatNumber(Integer seatNumber) {
        this.seatNumber = seatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.gmt_last_modify
     *
     * @return the value of t_car_model.gmt_last_modify
     *
     * @mbggenerated
     */
    public Date getGmtLastModify() {
        return gmtLastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.gmt_last_modify
     *
     * @param gmtLastModify the value for t_car_model.gmt_last_modify
     *
     * @mbggenerated
     */
    public void setGmtLastModify(Date gmtLastModify) {
        this.gmtLastModify = gmtLastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.gmt_create
     *
     * @return the value of t_car_model.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.gmt_create
     *
     * @param gmtCreate the value for t_car_model.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.gmt_modify
     *
     * @return the value of t_car_model.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.gmt_modify
     *
     * @param gmtModify the value for t_car_model.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.enable
     *
     * @return the value of t_car_model.enable
     *
     * @mbggenerated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.enable
     *
     * @param enable the value for t_car_model.enable
     *
     * @mbggenerated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.memo
     *
     * @return the value of t_car_model.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.memo
     *
     * @param memo the value for t_car_model.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.version
     *
     * @return the value of t_car_model.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.version
     *
     * @param version the value for t_car_model.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_model.series_id
     *
     * @return the value of t_car_model.series_id
     *
     * @mbggenerated
     */
    public String getSeriesId() {
        return seriesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_model.series_id
     *
     * @param seriesId the value for t_car_model.series_id
     *
     * @mbggenerated
     */
    public void setSeriesId(String seriesId) {
        this.seriesId = seriesId == null ? null : seriesId.trim();
    }
}