package com.uton.carsokApi.model;

import java.util.Date;

public class TCarBrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brand.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brand.brand_name
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brand.brand_id
     *
     * @mbggenerated
     */
    private String brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brand.gmt_last_modify
     *
     * @mbggenerated
     */
    private Date gmtLastModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brand.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brand.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brand.enable
     *
     * @mbggenerated
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brand.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brand.initial
     *
     * @mbggenerated
     */
    private String initial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brand.logo
     *
     * @mbggenerated
     */
    private String logo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brand.id
     *
     * @return the value of t_car_brand.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brand.id
     *
     * @param id the value for t_car_brand.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brand.brand_name
     *
     * @return the value of t_car_brand.brand_name
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brand.brand_name
     *
     * @param brandName the value for t_car_brand.brand_name
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brand.brand_id
     *
     * @return the value of t_car_brand.brand_id
     *
     * @mbggenerated
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brand.brand_id
     *
     * @param brandId the value for t_car_brand.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId == null ? null : brandId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brand.gmt_last_modify
     *
     * @return the value of t_car_brand.gmt_last_modify
     *
     * @mbggenerated
     */
    public Date getGmtLastModify() {
        return gmtLastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brand.gmt_last_modify
     *
     * @param gmtLastModify the value for t_car_brand.gmt_last_modify
     *
     * @mbggenerated
     */
    public void setGmtLastModify(Date gmtLastModify) {
        this.gmtLastModify = gmtLastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brand.gmt_create
     *
     * @return the value of t_car_brand.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brand.gmt_create
     *
     * @param gmtCreate the value for t_car_brand.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brand.gmt_modify
     *
     * @return the value of t_car_brand.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brand.gmt_modify
     *
     * @param gmtModify the value for t_car_brand.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brand.enable
     *
     * @return the value of t_car_brand.enable
     *
     * @mbggenerated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brand.enable
     *
     * @param enable the value for t_car_brand.enable
     *
     * @mbggenerated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brand.version
     *
     * @return the value of t_car_brand.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brand.version
     *
     * @param version the value for t_car_brand.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brand.initial
     *
     * @return the value of t_car_brand.initial
     *
     * @mbggenerated
     */
    public String getInitial() {
        return initial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brand.initial
     *
     * @param initial the value for t_car_brand.initial
     *
     * @mbggenerated
     */
    public void setInitial(String initial) {
        this.initial = initial == null ? null : initial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brand.logo
     *
     * @return the value of t_car_brand.logo
     *
     * @mbggenerated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brand.logo
     *
     * @param logo the value for t_car_brand.logo
     *
     * @mbggenerated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }
}